[tools]
deno = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:eza-community/eza" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:mvdan/sh" = "latest"
"github:neovim/neovim" = "latest"
"aqua:rhysd/dotfiles" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:starship/starship" = "latest"
"aqua:zellij-org/zellij" = "latest"

go = "latest"
java = "temurin-8"
node = "24"
usage = "latest"
delta = "latest"
rg = "latest"
gh = "latest"
